In [3]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [12]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [18]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [21]:
arr_2d[2,2]

45

In [28]:
arr_2d[1:,1:]

array([[25, 30],
       [40, 45]])

In [29]:
arr = np.arange(1,11)

In [30]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
bool_arr = arr > 5

In [38]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [33]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])