In [2]:
my_list = [1,2,3]

In [4]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [8]:
arr

array([1, 2, 3])

In [9]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [10]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones(4)

array([1., 1., 1., 1.])

In [17]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
np.random.rand(5)

array([0.57918646, 0.93452358, 0.02700655, 0.84854161, 0.54457778])

In [24]:
np.random.rand(5,5)

array([[0.21093018, 0.61666476, 0.57700472, 0.37209923, 0.18985027],
       [0.56573374, 0.90951849, 0.938313  , 0.49099853, 0.10330105],
       [0.44607413, 0.22819021, 0.19140509, 0.05013741, 0.95251593],
       [0.76699865, 0.50021894, 0.59068411, 0.24816868, 0.43114549],
       [0.71162217, 0.53478203, 0.29611315, 0.26639055, 0.38693501]])

In [26]:
np.random.randn(2)

array([-1.47400669, -0.81825286])

In [28]:
np.random.randn(4,4)

array([[-0.36903506,  0.13051991,  0.25761534,  0.25397548],
       [ 1.31103001, -0.00504947, -0.20070445,  1.53635391],
       [ 1.27110352, -1.50416512,  0.71008085,  0.53641155],
       [-0.36067264,  0.8046947 , -0.46625566, -0.37171404]])

In [30]:
np.random.randint(1,100,10)

array([ 7,  4, 75, 50, 29, 50, 96, 39, 55, 82])

In [32]:
arr = np.arange(25)

In [34]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
ranarr = np.random.randint(0,50,10)

In [45]:
ranarr

array([10,  7, 23, 37, 39, 39, 47, 10, 31, 35])

In [46]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [48]:
ranarr.min()

7

In [50]:
ranarr

array([10,  7, 23, 37, 39, 39, 47, 10, 31, 35])

In [52]:
ranarr.argmax()

6

In [54]:
ranarr.argmin()

1

In [56]:
arr.shape

(25,)

In [58]:
arr = arr.reshape(5,5)

In [60]:
arr.shape

(5, 5)

In [61]:
arr.dtype

dtype('int32')

In [62]:
from numpy.random import randint

In [63]:
randint(2,10)

8